steps:
- name: 'busybox'
  entrypoint: 'wget'
  args: ['-O', 'LT_Linux.zip', 'https://downloads.lambdatest.com/tunnel/v3/linux/64bit/LT_Linux.zip']
- name: 'bash'
  args: ['sh', 'startTunnel.sh']
- name: 'bash'
  args: ['unzip', 'LT_Linux.zip']
- name: 'bash'
  args: ['ls']
- name: 'bash'
  args: ['./LT']
- name: 'bash'
  args: ['ps', 'aux', '|', 'grep', 'LT']
- name: 'maven'
  entrypoint: 'mvn'
  args: ['test', '-P', 'single']
  env:
  - 'LT_USERNAME=${_LT_USERNAME}'
  - 'LT_ACCESS_KEY=${_LT_ACCESS_KEY}'
