steps:
- name: gcr.io/cloud-builders/docker
  args: ['run', '-d' , '--name=lt', '--network=cloudbuild', 'lambdatest/tunnel', '--user', '${_LT_USERNAME}', '--key', '${_LT_ACCESS_KEY}', '--infoAPIPort', '15000', '--tunnelName', 'GCloud']
#- name: jwilder/dockerize:0.6.1
#  args: ['dockerize', '-timeout=60s', '-wait=tcp://lt:15000']
- name: curlimages/curl
  args: ['-s', '--retry-connrefused', '--connect-timeout', '5', '--max-time', '5', '--retry', '30', '--retry-delay', '2', '--retry-max-time', '60', 'http://lt:15000/api/v1.0/info']
- name: 'ubuntu'
  args: ['sleep', '20']
- name: 'busybox'
  entrypoint: 'wget'
  args: ['-O', 'LT_Linux.zip', 'https://downloads.lambdatest.com/tunnel/v3/linux/64bit/LT_Linux.zip']
- name: 'bash'
  args: ['unzip', 'LT_Linux.zip']
- name: 'bash'
  args: ['sh', 'startTunnel.sh']
- name: 'bash'
  args: ['ps', 'aux', '|', 'grep', 'LT']
- name: 'bash'
  args: ['ls']
- name: 'bash'
  args: ['pwd']
- name: 'bash'
  args: ['chmod', '755', 'LT']
- name: 'ubuntu'
  args: ['apt-get', 'update']
#- name: 'ubuntu'
#  args: ['dpkg-reconfigure', 'ca-certificates']
#- name: 'ubuntu'
#  args: ['apt-get', 'install', '-y', 'ca-certificates']
#- name: 'ubuntu'
#  args: ['update-ca-certificates']
- name: 'ubuntu'
  args: ['./LT', '--user', '${_LT_USERNAME}', '--key', '${_LT_ACCESS_KEY}', '--tunnelName', 'GCloud', '--env', 'prod', '--verbose', '--mitm', '--load-balanced', '&']
- name: 'bash'
  args: ['ps', 'aux', '|', 'grep', 'LT']
- name: 'maven'
  entrypoint: 'mvn'
  args: ['test', '-P', 'single']
  env:
  - 'LT_USERNAME=${_LT_USERNAME}'
  - 'LT_ACCESS_KEY=${_LT_ACCESS_KEY}'

